[auth]
client_id = "j6yvyCMUVPEPwroVUWv3syeGSag8ae0V"
client_secret = "nsTAqeNKfaWR4qV4AR45gDiPlqiBrCMCguYcGMKpw5L_4Gfp0V"
redirect_uri = "http://localhost:8501/"
cookie_secret = "a_very_random_secure_string_generated"  # create a random one, min 32 chars!
server_metadata_url = "https://dev-i21hjwtofgm1zi1v.us.auth0.com/.well-known/openid-configuration"
